### ISSUE TITLE
Merge docs repo

### ISSUE THREAD

**Issue by joepio** [atomicdata-dev/atomic-server#719]
The [Documentation repo](https://github.com/atomicdata-dev/atomic-data-docs) is separate from this one. This was done for two reasons:

- Github pages hosting. We can switch to netlify, no problems there.
- Make sure the Docs stand on their own and do not rely on any specific implementation. The spec is not bound to one app. We should keep this philosophy going and make a clear separation between spec and docs.

## Why merging is a good idea

- Users of AtomicServer will need to understand the basics of Atomic Data (e.g. JSON AD, Commits). Having them all in one place makes a lot of sense.
- People interested in the spec can more easily "get started" if the docs also tell them how to do so.

## TODO list

- [x] Archive old repo
- [ ] Move discussions / issues
- [x] Add tag
- [x] Publish pages using Netlify
- [x] Change DNS settings
