### ISSUE TITLE
Site Class / ontology

### ISSUE THREAD

**Issue by joepio** [atomicdata-dev/atomic-server#923]
Building websites with AtomicServer should be as easy as possible. We already have an [`Article` class](https://atomicdata.dev/classes/Article) which we use on some pages in production ([example](https://denkmee.drechtstedenenergie.nl/)). We also have an [`argu-site`](https://atomicdata.dev/Folder/wp8ame4nqf/MYJkFKGEKz) which I made when migrating a bunch of our Argu customers to AtomicServer. This Class has some issues:

- The URL is odd 
- It's tightly coupled to Argu and [this github project](https://github.com/ontola/atomic-argu)

## Customizability vs interoperability

- We want developers to be able to very easily make any changes to classes & properties 
- We want to encourage re-use of classes and properties to improve interoperability

How can get both:

- We host standard classes (e.g. `/classes/Site`, `/classes/MenuItem` `/classes/Article`)
- We host the properties (e.g.`/properties/menu-item`)
- User clones the classes, turning them into local classes. 

## Todo

- [ ] `Site` class 
- [ ] GUI for this class
- [ ] `menu-item` list of pages to link to
- [ ] `redeploy-link` item that when opened, triggers a redeploy
- [ ] `default-image` for seo / socials
- [ ] `default-description`
- [ ] `social-links`, maybe just add a bunch of links and assume some icons
- [ ] mapping onto a [`config.toml` from Zola](https://github.com/terraphim/terraphim.ai/blob/main/config.toml) might make sense
- [ ] [`tags`](https://atomicdata.dev/properties/tags). We already have tags in [`Table` class](https://atomicdata.dev/classes/Table)
- [ ] Add an Ontology for websites? Or stick to one class?
- [ ] Update [`atomic-sveltekit-demo`](https://github.com/atomicdata-dev/atomic-sveltekit-demo) to use this new class, update readme.

**Comment by joepio** [comment]
Polle went for a very different approach in #952, closing
