### ISSUE TITLE
`create-template` package to `npm create @tomic/template`

### ISSUE THREAD

**Issue by joepio** [atomicdata-dev/atomic-server#952]
We could make a `create-template` package that allows users to do things like `npm create @tomic/template`
Since these are just executable scripts we can do things like generate a users ontologies and have some options like what framework to use.

_Originally posted by @Polleps in https://github.com/atomicdata-dev/atomic-server/issues/923#issuecomment-2304394809_

## Goals

- Make it easier for devs to start a website using `@tomic/lib` and `@tomic/svelte`
- Dogfeed our APIs so we make them as easy as possible for our main usecase (Headless CMS)
- Test libs in a project in the CI (instead of just relying on unit tests)

## TODO

- [x] Template (sveltekit?) project, should be minimal
  - [ ] Render Articles
  - [ ] Render a Collection (using some custom view)
  - [x] Search bar
  - [ ] Readme that mentions the CLI and links to docs where needed
- [ ] Template ontology (article, menu item)
- [ ] cli action that copies a folder
- [ ] link to an ontology to create types
- [ ] e2e tests (should use `pnpm link`)
- [ ] Publish new NPM package
- [ ] Publish it to netlify (and add docs)
- [ ] Publish it to cloudflar (and add docs)

**Comment by joepio** [comment]
Can you commit + push + open a draft PR @Polleps? @AlexMikhalev and me would also like to see the progress in this!
